# Configure your watchtower private keys here
watchtower_private_keys:
  - <WatchTower-1-private-key>
  - <WatchTower-2-private-key>
  - <WatchTower-3-private-key>


operator_private_key: <Operator-private-key>
operator_registry_address: <OperatorRegistry-contract-address>


eth_rpc_url: <RPC-URL>
chain_id: <ChainID>
gas_limit: <Gas-limit>
